<?php

namespace EmailBundle\Repository;

/**
 * EmailLogContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailLogContentRepository extends \Doctrine\ORM\EntityRepository
{
}
