<?php

namespace EmailBundle\Repository;

use EmailBundle\Entity\EmailLog;

/**
 * EmailLogRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailLogRepository extends \Doctrine\ORM\EntityRepository
{
    public function isEmailSent($templateName, $email, $emailType, $eventType, $event)
    {
        $qb = $this->_em->createQueryBuilder('el');
        $qb->select('count(el.id)')
            ->from(EmailLog::class, 'el')
            ->where('el.emailAddress LIKE :email')
            ->andWhere('el.emailType LIKE :type')
            ->andWhere('el.eventType = :eventType')
            ->andWhere('el.template LIKE :template')
            ->andWhere('el.status = 0')
            ->setParameters(array(
                'email' => $email,
                'type' => $emailType,
                'template' => $templateName,
                'eventType' => $eventType
            ));
        if ($event != null) {
            $qb->andWhere('el.event = :event')
            ->setParameter('event', $event);
        }

        $result = $qb->getQuery()->getSingleScalarResult();
        return $result > 0;
    }
}
