<?php

namespace EmailBundle\Repository;

/**
 * EmailLogStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailLogStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
