admin:
    resource: '@AdminBundle/Controller/'
    type:     annotation
    prefix:   /admin

app_unsubscribe:
    resource: "@AppBundle/Controller/UnsubscribeController.php"
    type: annotation
    
app_confirm:
    resource: "@AppBundle/Controller/ConfirmRegistrationController.php"
    type: annotation

app_default:
    resource: "@AppBundle/Controller/DefaultController.php"
    type: annotation

template:
    resource: '@TemplateBundle/Controller/'
    type:     annotation

email:
    resource: '@EmailBundle/Controller/'
    type:     annotation

logout:
    path: /admin/logout
