# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AdminBundle\Entity\Admin:
            algorithm: sha512

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        mysql_provider:
            entity:
                class: AdminBundle\Entity\Admin
                property: email

    access_control:
        - { path: ^/admin/?(?!/?login).*, roles: ROLE_ADMIN }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true
            logout:
                path: /logout
                target: /login
            form_login:
                login_path: login
                check_path: login
                always_use_default_target_path: true
                provider: mysql_provider
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
