<?php

namespace AdminBundle\Repository;

/**
 * AttendeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttendeeRepository extends \Doctrine\ORM\EntityRepository
{
}
