<?php

namespace AdminBundle\Repository;

/**
 * EventTypeLanguagesRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventTypeLanguagesRepository extends \Doctrine\ORM\EntityRepository
{
}
