<?php

namespace AdminBundle\Repository;

/**
 * EventLanguagesRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventLanguagesRepository extends \Doctrine\ORM\EntityRepository
{
}
