<?php

namespace AdminBundle\Repository;

/**
 * EventRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNearingEvents()
    {
        $qb = $this->_em->createQueryBuilder('e');
        $qb->select('e')
            ->from('AdminBundle:Event', 'e')
            ->where('DAYOFYEAR(DATE_ADD(CURRENT_DATE(), e.notificationThreshold, \'DAY\')) = DAYOFYEAR(e.dateTime)');

        return $qb->getQuery()->getResult();
    }
}
