<?php

namespace AdminBundle\Repository;

/**
 * EventOrganizersRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventOrganizersRepository extends \Doctrine\ORM\EntityRepository
{
}
