<?php

namespace AdminBundle\Repository;

/**
 * EventTypeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventTypeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getBySlug($slug)
    {
        $qb = $this->_em->createQueryBuilder('et');
        $qb->select('et')
            ->from('AdminBundle:EventType', 'et')
            ->where('et.slug = :slug')
            ->setParameter('slug', $slug);

        return $qb->getQuery()->getResult();
    }
}
