<?php

namespace AdminBundle\Repository;

use AdminBundle\Entity\Organizer;

/**
 * OrganizerRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizerRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOrganizersByEmail($term)
    {
        $qb = $this->_em->createQueryBuilder('o');
        $qb->select('o')
            ->from(Organizer::class, 'o')
            ->where('o.email LIKE :email')
            ->setParameter('email', '%'.$term.'%');

        return $qb->getQuery()->getResult();
    }
}
