<?php

namespace AdminBundle\Repository;

/**
 * OrganizerRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizerRepository extends \Doctrine\ORM\EntityRepository
{
}
