<?php

namespace AdminBundle\Repository;

use AdminBundle\Entity\Registration;

/**
 * RegistrationRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistrationRepository extends \Doctrine\ORM\EntityRepository
{
    public function generateCodeForEvent($eventId)
    {
        $qb = $this->_em->createQueryBuilder('r');
        $qb->select('MAX(r.code)')
            ->from(Registration::class, 'r')
            ->where('r.event = :eventId')
            ->setParameter('eventId', $eventId);

        return $qb->getQuery()->getSingleScalarResult() + 1;
    }
}
